<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, SoftDeletes;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'role_id',
        'username',
        'full_name',
        'email',
        'password',
        'phone_number',
        'rt_code',
        'status',
        'last_login_at',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'password' => 'hashed',
        'last_login_at' => 'datetime',
    ];

    /**
     * Get the role associated with the user.
     *
     * @return BelongsTo<Role, User>
     */
    public function role(): BelongsTo
    {
        return $this->belongsTo(Role::class, 'role_id');
    }

    /**
     * Get audit logs generated by this user.
     *
     * @return HasMany<AuditLog>
     */
    public function auditLogs(): HasMany
    {
        return $this->hasMany(AuditLog::class, 'user_id');
    }

    /**
     * Determine if the user has a specific role.
     */
    public function hasRole(string $roleName): bool
    {
        return $this->role !== null && $this->role->name === $roleName;
    }

    /**
     * Determine if the user has any of the given roles.
     *
     * @param  array<int, string>  $roleNames
     */
    public function hasAnyRole(array $roleNames): bool
    {
        if ($this->role === null) {
            return false;
        }

        return in_array($this->role->name, $roleNames, true);
    }

    /**
     * Determine if the user has a specific permission.
     */
    public function hasPermission(string $permissionName): bool
    {
        if ($this->role === null) {
            return false;
        }

        return $this->role->hasPermission($permissionName);
    }

    /**
     * Catatan iuran yang dicatat oleh user ini (sebagai Ketua RT).
     *
     * @return HasMany<CatatanIuran>
     */
    public function recordedIurans(): HasMany
    {
        return $this->hasMany(CatatanIuran::class, 'recorded_by_user_id');
    }

    /**
     * Catatan iuran yang diverifikasi oleh user ini (sebagai Bendahara RW).
     *
     * @return HasMany<CatatanIuran>
     */
    public function approvedIurans(): HasMany
    {
        return $this->hasMany(CatatanIuran::class, 'approved_by_user_id');
    }

    /**
     * Kas keluar yang dicatat oleh user ini (sebagai Bendahara RW).
     *
     * @return HasMany<KasKeluar>
     */
    public function recordedKasKeluars(): HasMany
    {
        return $this->hasMany(KasKeluar::class, 'recorded_by_user_id');
    }

    /**
     * Kas keluar yang disetujui oleh user ini (sebagai Ketua RW).
     *
     * @return HasMany<KasKeluar>
     */
    public function approvedKasKeluars(): HasMany
    {
        return $this->hasMany(KasKeluar::class, 'approved_by_user_id');
    }

    /**
     * Informasi publik yang dipublikasikan oleh user ini.
     *
     * @return HasMany<InformasiPublik>
     */
    public function informasiPubliks(): HasMany
    {
        return $this->hasMany(InformasiPublik::class, 'published_by_user_id');
    }
}
